package ec.com.levelap.tcc.wsdl.clientes;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-11-07T16:51:01.776-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://clientes.tcc.com.co/", name = "InformacionRemesasHttpGet")
@XmlSeeAlso({ObjectFactory.class})
public interface InformacionRemesasHttpGet {
}
