package ec.com.levelap.tcc.wsdl.clientes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-11-07T16:51:01.725-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://clientes.tcc.com.co/", name = "InformacionRemesasSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface InformacionRemesasSoap {

    /**
     * Consulta la información de un arreglo de remesas de tipo clsRemesa, en donde el número de cada remesa a consultar se ingresa en la propiedad NroRemesa.
     */
    @WebMethod(operationName = "ConsultarInformacionRemesasVariasSmartphone", action = "http://clientes.tcc.com.co/ConsultarInformacionRemesasVariasSmartphone")
    @RequestWrapper(localName = "ConsultarInformacionRemesasVariasSmartphone", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesasVariasSmartphone")
    @ResponseWrapper(localName = "ConsultarInformacionRemesasVariasSmartphoneResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesasVariasSmartphoneResponse")
    public void consultarInformacionRemesasVariasSmartphone(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(mode = WebParam.Mode.INOUT, name = "arrRemesas", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<ArrayOfClsRemesa> arrRemesas,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Recibe una lista de remesas para consultar el estatus de las remesas en dicho rango. Devuelve la información consultada en formato XML
     */
    @WebMethod(operationName = "ConsultarEstatusRemesasLista", action = "http://clientes.tcc.com.co/ConsultarEstatusRemesasLista")
    @RequestWrapper(localName = "ConsultarEstatusRemesasLista", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasLista")
    @ResponseWrapper(localName = "ConsultarEstatusRemesasListaResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasListaResponse")
    public void consultarEstatusRemesasLista(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "remesas", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String remesas,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Recibe el código de una novedad y devuelve la información del seguimiento de dicha novedad en formato XML
     */
    @WebMethod(operationName = "ConsultaSeguimientoNovedades", action = "http://clientes.tcc.com.co/ConsultaSeguimientoNovedades")
    @RequestWrapper(localName = "ConsultaSeguimientoNovedades", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultaSeguimientoNovedades")
    @ResponseWrapper(localName = "ConsultaSeguimientoNovedadesResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultaSeguimientoNovedadesResponse")
    public void consultaSeguimientoNovedades(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "codNovedad", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String codNovedad,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Recibe una lista de remesas para consultar el estatus de las remesas en dicho rango con un origen determinado. Devuelve la información consultada en formato XML
     */
    @WebMethod(operationName = "ConsultarEstatusRemesasRangoCD", action = "http://clientes.tcc.com.co/ConsultarEstatusRemesasRangoCD")
    @RequestWrapper(localName = "ConsultarEstatusRemesasRangoCD", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasRangoCD")
    @ResponseWrapper(localName = "ConsultarEstatusRemesasRangoCDResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasRangoCDResponse")
    public void consultarEstatusRemesasRangoCD(
        @WebParam(name = "clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "strCodigoCD", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String strCodigoCD,
        @WebParam(name = "strRemInicial", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String strRemInicial,
        @WebParam(name = "strRemFinal", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String strRemFinal,
        @WebParam(mode = WebParam.Mode.INOUT, name = "informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Consulta los puntos de venta cercanos a la latitud y longitud suministrada
     */
    @WebMethod(operationName = "ConsultarPDVsCercanos", action = "http://clientes.tcc.com.co/ConsultarPDVsCercanos")
    @RequestWrapper(localName = "ConsultarPDVsCercanos", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarPDVsCercanos")
    @ResponseWrapper(localName = "ConsultarPDVsCercanosResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarPDVsCercanosResponse")
    public void consultarPDVsCercanos(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "Latitud", targetNamespace = "http://clientes.tcc.com.co/")
        double latitud,
        @WebParam(name = "Longitud", targetNamespace = "http://clientes.tcc.com.co/")
        double longitud,
        @WebParam(name = "CercaniaKMS", targetNamespace = "http://clientes.tcc.com.co/")
        double cercaniaKMS,
        @WebParam(mode = WebParam.Mode.INOUT, name = "PDVs", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<ArrayOfClsPuntoDeVenta> pdVs,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Consulta la información de un arreglo de remesas de tipo clsRemesa, en donde el número de cada remesa a consultar se ingresa en la propiedad NroRemesa (Fuente OSB)
     */
    @WebMethod(operationName = "ConsultarInformacionRemesasEstados", action = "http://clientes.tcc.com.co/ConsultarInformacionRemesasEstados")
    @RequestWrapper(localName = "ConsultarInformacionRemesasEstados", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesasEstados")
    @ResponseWrapper(localName = "ConsultarInformacionRemesasEstadosResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesasEstadosResponse")
    public void consultarInformacionRemesasEstados(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "remesas", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.wsdl.clientes.ArrayOfRemesa remesas,
        @WebParam(mode = WebParam.Mode.INOUT, name = "remesasrespuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<ArrayOfRemesaEstados> remesasrespuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Consulta las remesas de un cliente para un rango de fechas. Devuelve la información consultada en formato XML
     */
    @WebMethod(operationName = "ConsultarEstatusRemesasRangoFechas", action = "http://clientes.tcc.com.co/ConsultarEstatusRemesasRangoFechas")
    @RequestWrapper(localName = "ConsultarEstatusRemesasRangoFechas", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasRangoFechas")
    @ResponseWrapper(localName = "ConsultarEstatusRemesasRangoFechasResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasRangoFechasResponse")
    public void consultarEstatusRemesasRangoFechas(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "fechaInicial", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String fechaInicial,
        @WebParam(name = "fechaFinal", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String fechaFinal,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Recibe una lista de remesas para consultar el estatus de las remesas en dicho rango. Devuelve la información consultada en formato XML
     */
    @WebMethod(operationName = "ConsultarEstatusRemesasListaOSB", action = "http://clientes.tcc.com.co/ConsultarEstatusRemesasListaOSB")
    @RequestWrapper(localName = "ConsultarEstatusRemesasListaOSB", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasListaOSB")
    @ResponseWrapper(localName = "ConsultarEstatusRemesasListaOSBResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasListaOSBResponse")
    public void consultarEstatusRemesasListaOSB(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "remesas", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String remesas,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Recibe un documento de referencia, una clave de remesa, una fecha inicial, una fecha final, el login del contacto y el estado de la remesa y devuelve la información de la remesa, el tracking, las novedades y el seguimiento
     */
    @WebMethod(operationName = "ConsultarRemesasTrackingMensajeriaCRC", action = "http://clientes.tcc.com.co/ConsultarRemesasTrackingMensajeriaCRC")
    @RequestWrapper(localName = "ConsultarRemesasTrackingMensajeriaCRC", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarRemesasTrackingMensajeriaCRC")
    @ResponseWrapper(localName = "ConsultarRemesasTrackingMensajeriaCRCResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarRemesasTrackingMensajeriaCRCResponse")
    public void consultarRemesasTrackingMensajeriaCRC(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "DocReferencia", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String docReferencia,
        @WebParam(name = "Remesa", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String remesa,
        @WebParam(name = "FechaInicial", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String fechaInicial,
        @WebParam(name = "FechaFinal", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String fechaFinal,
        @WebParam(name = "UsuarioLogin", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String usuarioLogin,
        @WebParam(name = "EstadoRemesa", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.Integer estadoRemesa,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "ConsultarRemesasTrackingMensajeriaCRCResult", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<ArrayOfClsInfoRemesa> consultarRemesasTrackingMensajeriaCRCResult
    );

    /**
     * Recibe una lista de remesas para consultar el estatus de las remesas en dicho rango. Devuelve la información consultada en formato XML
     */
    @WebMethod(operationName = "ConsultarInformacionRemesasDetalle", action = "http://clientes.tcc.com.co/ConsultarInformacionRemesasDetalle")
    @RequestWrapper(localName = "ConsultarInformacionRemesasDetalle", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesasDetalle")
    @ResponseWrapper(localName = "ConsultarInformacionRemesasDetalleResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesasDetalleResponse")
    @WebResult(name = "ConsultarInformacionRemesasDetalleResult", targetNamespace = "http://clientes.tcc.com.co/")
    public ec.com.levelap.tcc.wsdl.clientes.TpSalida consultarInformacionRemesasDetalle(
        @WebParam(name = "consultar", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.wsdl.clientes.TpEntrada consultar
    );

    /**
     * Recibe una clave de remesa y consulta la información de las novedades correspondientes a esa remesa en formato XML
     */
    @WebMethod(operationName = "ConsultaInformacionNovedades", action = "http://clientes.tcc.com.co/ConsultaInformacionNovedades")
    @RequestWrapper(localName = "ConsultaInformacionNovedades", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultaInformacionNovedades")
    @ResponseWrapper(localName = "ConsultaInformacionNovedadesResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultaInformacionNovedadesResponse")
    public void consultaInformacionNovedades(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "claveRemesa", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String claveRemesa,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Recibe una clave de remesa y consulta la información básica correspondiente a esa remesa. Devuelve la información consultada en formato XML
     */
    @WebMethod(operationName = "ConsultarInformacionRemesa", action = "http://clientes.tcc.com.co/ConsultarInformacionRemesa")
    @RequestWrapper(localName = "ConsultarInformacionRemesa", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesa")
    @ResponseWrapper(localName = "ConsultarInformacionRemesaResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesaResponse")
    public void consultarInformacionRemesa(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "claveRemesa", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String claveRemesa,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Recibe una lista de remesas para consultar el estatus de las remesas en dicho rango. Devuelve la información consultada en formato XML
     */
    @WebMethod(operationName = "ConsultarEstatusRemesasListaBE", action = "http://clientes.tcc.com.co/ConsultarEstatusRemesasListaBE")
    @RequestWrapper(localName = "ConsultarEstatusRemesasListaBE", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasListaBE")
    @ResponseWrapper(localName = "ConsultarEstatusRemesasListaBEResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasListaBEResponse")
    public void consultarEstatusRemesasListaBE(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "remesas", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String remesas,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Consulta un status corto de las remesas de un cliente para un rango de fechas. Devuelve la información consultada en formato XML
     */
    @WebMethod(operationName = "ConsultarEstatusCortoRemesasRangoFechas", action = "http://clientes.tcc.com.co/ConsultarEstatusCortoRemesasRangoFechas")
    @RequestWrapper(localName = "ConsultarEstatusCortoRemesasRangoFechas", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusCortoRemesasRangoFechas")
    @ResponseWrapper(localName = "ConsultarEstatusCortoRemesasRangoFechasResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusCortoRemesasRangoFechasResponse")
    public void consultarEstatusCortoRemesasRangoFechas(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "fechaInicial", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String fechaInicial,
        @WebParam(name = "fechaFinal", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String fechaFinal,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Consulta las remesas de un cliente para un rango de fechas. Devuelve la información consultada en formato XML, con tipo y número de documento referencia
     */
    @WebMethod(operationName = "ConsultarEstatusRemesasRangoFechasDocRef", action = "http://clientes.tcc.com.co/ConsultarEstatusRemesasRangoFechasDocRef")
    @RequestWrapper(localName = "ConsultarEstatusRemesasRangoFechasDocRef", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasRangoFechasDocRef")
    @ResponseWrapper(localName = "ConsultarEstatusRemesasRangoFechasDocRefResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasRangoFechasDocRefResponse")
    public void consultarEstatusRemesasRangoFechasDocRef(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "fechaInicial", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String fechaInicial,
        @WebParam(name = "fechaFinal", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String fechaFinal,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Consulta la información de un arreglo de remesas de tipo clsRemesa, en donde el número de cada remesa a consultar se ingresa en la propiedad NroRemesa (Fuente OSB)
     */
    @WebMethod(operationName = "ConsultarInformacionRemesasVariasSmartphoneOSB", action = "http://clientes.tcc.com.co/ConsultarInformacionRemesasVariasSmartphoneOSB")
    @RequestWrapper(localName = "ConsultarInformacionRemesasVariasSmartphoneOSB", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesasVariasSmartphoneOSB")
    @ResponseWrapper(localName = "ConsultarInformacionRemesasVariasSmartphoneOSBResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesasVariasSmartphoneOSBResponse")
    public void consultarInformacionRemesasVariasSmartphoneOSB(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "arrRemesasIn", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.wsdl.clientes.ArrayOfClsRemesa arrRemesasIn,
        @WebParam(mode = WebParam.Mode.INOUT, name = "arrRemesasOUT", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<ArrayOfClsRemesa> arrRemesasOUT,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Consulta la información de la remesa cuyo número se ingrese en la propiedad NroRemesa.
     */
    @WebMethod(operationName = "ConsultarInformacionRemesaSmartphone", action = "http://clientes.tcc.com.co/ConsultarInformacionRemesaSmartphone")
    @RequestWrapper(localName = "ConsultarInformacionRemesaSmartphone", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesaSmartphone")
    @ResponseWrapper(localName = "ConsultarInformacionRemesaSmartphoneResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesaSmartphoneResponse")
    public void consultarInformacionRemesaSmartphone(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Remesa", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<ClsRemesa> remesa,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Recibe un documento referencia para consultar el estatus de la remesa segun el documento enviado. Devuelve la información consultada en formato XML
     */
    @WebMethod(operationName = "ConsultarEstatusRemesasDocReferenciaOSB", action = "http://clientes.tcc.com.co/ConsultarEstatusRemesasDocReferenciaOSB")
    @RequestWrapper(localName = "ConsultarEstatusRemesasDocReferenciaOSB", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasDocReferenciaOSB")
    @ResponseWrapper(localName = "ConsultarEstatusRemesasDocReferenciaOSBResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasDocReferenciaOSBResponse")
    public void consultarEstatusRemesasDocReferenciaOSB(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "DocumentoReferencia", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String documentoReferencia,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Recibe un documento de referencia, una clave de remesa, una fecha inicial, una fecha final, el loguin del contacto y el estado de la remesa y devuelve la información de la remesa, el tracking,las novedades y el seguimiento
     */
    @WebMethod(operationName = "ConsultarRemesasTrackingMensajeria", action = "http://clientes.tcc.com.co/ConsultarRemesasTrackingMensajeria")
    @RequestWrapper(localName = "ConsultarRemesasTrackingMensajeria", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarRemesasTrackingMensajeria")
    @ResponseWrapper(localName = "ConsultarRemesasTrackingMensajeriaResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarRemesasTrackingMensajeriaResponse")
    public void consultarRemesasTrackingMensajeria(
        @WebParam(name = "clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "docReferencia", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String docReferencia,
        @WebParam(name = "remesa", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String remesa,
        @WebParam(name = "fechaInicial", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String fechaInicial,
        @WebParam(name = "fechaFinal", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String fechaFinal,
        @WebParam(name = "usuarioLoguin", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String usuarioLoguin,
        @WebParam(name = "estadoRemesa", targetNamespace = "http://clientes.tcc.com.co/")
        int estadoRemesa,
        @WebParam(mode = WebParam.Mode.INOUT, name = "infoRemesaTracking", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> infoRemesaTracking,
        @WebParam(mode = WebParam.Mode.INOUT, name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Consulta la información de las remesas de hasta 3 números de relación de envíos devolviendo la información en el arreglo de clases de tipo clsRemesa arrRemesas.
     */
    @WebMethod(operationName = "ConsultarRelacionesEnvioSmartphone", action = "http://clientes.tcc.com.co/ConsultarRelacionesEnvioSmartphone")
    @RequestWrapper(localName = "ConsultarRelacionesEnvioSmartphone", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarRelacionesEnvioSmartphone")
    @ResponseWrapper(localName = "ConsultarRelacionesEnvioSmartphoneResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarRelacionesEnvioSmartphoneResponse")
    public void consultarRelacionesEnvioSmartphone(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "Relacion1", targetNamespace = "http://clientes.tcc.com.co/")
        int relacion1,
        @WebParam(name = "Relacion2", targetNamespace = "http://clientes.tcc.com.co/")
        int relacion2,
        @WebParam(name = "Relacion3", targetNamespace = "http://clientes.tcc.com.co/")
        int relacion3,
        @WebParam(mode = WebParam.Mode.INOUT, name = "arrRemesas", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<ArrayOfClsRemesa> arrRemesas,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Recibe una lista de documentos referencia del cliente para consultar el estatus de las remesas en dicho rango. Devuelve la información consultada en formato XML
     */
    @WebMethod(operationName = "ConsultarEstatusRemesasListaDocumentos", action = "http://clientes.tcc.com.co/ConsultarEstatusRemesasListaDocumentos")
    @RequestWrapper(localName = "ConsultarEstatusRemesasListaDocumentos", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasListaDocumentos")
    @ResponseWrapper(localName = "ConsultarEstatusRemesasListaDocumentosResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasListaDocumentosResponse")
    public void consultarEstatusRemesasListaDocumentos(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "documentos", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String documentos,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Recibe una remesa inicial y una remesa final para consultar el estatus de las remesas en dicho rango. Devuelve la información consultada en formato XML
     */
    @WebMethod(operationName = "ConsultarEstatusRemesasRango", action = "http://clientes.tcc.com.co/ConsultarEstatusRemesasRango")
    @RequestWrapper(localName = "ConsultarEstatusRemesasRango", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasRango")
    @ResponseWrapper(localName = "ConsultarEstatusRemesasRangoResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasRangoResponse")
    public void consultarEstatusRemesasRango(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "strRemInicial", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String strRemInicial,
        @WebParam(name = "strRemFinal", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String strRemFinal,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Recibe una lista de remesas para consultar el estatus de las remesas de dicha lista con un centro de distribución de origen. Devuelve la información consultada en formato XML
     */
    @WebMethod(operationName = "ConsultarEstatusRemesasListaCD", action = "http://clientes.tcc.com.co/ConsultarEstatusRemesasListaCD")
    @RequestWrapper(localName = "ConsultarEstatusRemesasListaCD", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasListaCD")
    @ResponseWrapper(localName = "ConsultarEstatusRemesasListaCDResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarEstatusRemesasListaCDResponse")
    public void consultarEstatusRemesasListaCD(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "remesas", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String remesas,
        @WebParam(name = "strCodigoCD", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String strCodigoCD,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Informacion", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> informacion,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );

    /**
     * Consulta la información de un arreglo de remesas de tipo clsRemesaUEN, en donde el número de cada remesa a consultar se ingresa en la propiedad NroRemesa y Unidad de Negocio (Fuente OSB)
     */
    @WebMethod(operationName = "ConsultarInformacionRemesasEstadosUEN", action = "http://clientes.tcc.com.co/ConsultarInformacionRemesasEstadosUEN")
    @RequestWrapper(localName = "ConsultarInformacionRemesasEstadosUEN", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesasEstadosUEN")
    @ResponseWrapper(localName = "ConsultarInformacionRemesasEstadosUENResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.wsdl.clientes.ConsultarInformacionRemesasEstadosUENResponse")
    public void consultarInformacionRemesasEstadosUEN(
        @WebParam(name = "Clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "remesas", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.wsdl.clientes.ArrayOfRemesaUEN remesas,
        @WebParam(mode = WebParam.Mode.INOUT, name = "remesasrespuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<ArrayOfRemesaEstados> remesasrespuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "Mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje
    );
}
