package ec.com.levelap.tcc.wsdl.clientes;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2018-04-06T18:53:43.562-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://clientes.tcc.com.co/", name = "wsDespachosHttpGet")
@XmlSeeAlso({ObjectFactory.class, ec.com.levelap.tcc.wsdl.xsd.ObjectFactory.class})
public interface WsDespachosHttpGet {
}
