package ec.com.levelap.tcc.wsdl.clientes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-08-08T16:23:21.075-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "wsDespachos", 
                  wsdlLocation = "http://clientes.tcc.com.co/servicios/wsDespachos.asmx?WSDL",
                  targetNamespace = "http://clientes.tcc.com.co/") 
public class WsDespachos extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://clientes.tcc.com.co/", "wsDespachos");
    public final static QName WsDespachosHttpGet = new QName("http://clientes.tcc.com.co/", "wsDespachosHttpGet");
    public final static QName WsDespachosSoap = new QName("http://clientes.tcc.com.co/", "wsDespachosSoap");
    public final static QName WsDespachosSoap12 = new QName("http://clientes.tcc.com.co/", "wsDespachosSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://clientes.tcc.com.co/servicios/wsDespachos.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsDespachos.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://clientes.tcc.com.co/servicios/wsDespachos.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public WsDespachos(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsDespachos(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsDespachos() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsDespachos(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsDespachos(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsDespachos(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WsDespachosHttpGet
     */
    @WebEndpoint(name = "wsDespachosHttpGet")
    public WsDespachosHttpGet getWsDespachosHttpGet() {
        return super.getPort(WsDespachosHttpGet, WsDespachosHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsDespachosHttpGet
     */
    @WebEndpoint(name = "wsDespachosHttpGet")
    public WsDespachosHttpGet getWsDespachosHttpGet(WebServiceFeature... features) {
        return super.getPort(WsDespachosHttpGet, WsDespachosHttpGet.class, features);
    }
    /**
     *
     * @return
     *     returns WsDespachosSoap
     */
    @WebEndpoint(name = "wsDespachosSoap")
    public WsDespachosSoap getWsDespachosSoap() {
        return super.getPort(WsDespachosSoap, WsDespachosSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsDespachosSoap
     */
    @WebEndpoint(name = "wsDespachosSoap")
    public WsDespachosSoap getWsDespachosSoap(WebServiceFeature... features) {
        return super.getPort(WsDespachosSoap, WsDespachosSoap.class, features);
    }
    /**
     *
     * @return
     *     returns WsDespachosSoap
     */
    @WebEndpoint(name = "wsDespachosSoap12")
    public WsDespachosSoap getWsDespachosSoap12() {
        return super.getPort(WsDespachosSoap12, WsDespachosSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsDespachosSoap
     */
    @WebEndpoint(name = "wsDespachosSoap12")
    public WsDespachosSoap getWsDespachosSoap12(WebServiceFeature... features) {
        return super.getPort(WsDespachosSoap12, WsDespachosSoap.class, features);
    }

}
