/**
 * @Copyright:	Levelap 2017
 * @Class:		KushkiException.java
 * @Created:	23-03-2016
 * @Updated:	
 */
package ec.com.levelap.kushki;

/**
 * Exception to propagate errors generated by API RESTful by Kushki.
 * 
 * @author Luis García Castro.
 */
public class KushkiException extends Exception {

	private static final long serialVersionUID = -4249010878907604812L;

	private String code;

	private String message;

	/**
	 * {@link KushkiException} default constructor.
	 * 
	 * @param cause
	 */
	public KushkiException(Throwable cause) {
		super(cause);
	}

	/**
	 * {@link KushkiException} constructor with parameters.
	 * 
	 * @param code
	 *            Kushki error code response.
	 * @param message
	 *            Kushki error message response.
	 */
	public KushkiException(final String code, final String message) {
		this.code = code;
		this.message = message;
	}

	/* GETTERS AND SETTERS */

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
