//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 01:29:20 PM COT 
//


package ec.com.levelap.tcc.entity.wsrecogidas;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ec.com.levelap.tcc.entity.wsrecogidas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ec.com.levelap.tcc.entity.wsrecogidas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClsClienteSolicitante }
     * 
     */
    public ClsClienteSolicitante createClsClienteSolicitante() {
        return new ClsClienteSolicitante();
    }

    /**
     * Create an instance of {@link ClsClienteRemitenteConNroRemesa }
     * 
     */
    public ClsClienteRemitenteConNroRemesa createClsClienteRemitenteConNroRemesa() {
        return new ClsClienteRemitenteConNroRemesa();
    }

    /**
     * Create an instance of {@link ArrayOfClsRecogida }
     * 
     */
    public ArrayOfClsRecogida createArrayOfClsRecogida() {
        return new ArrayOfClsRecogida();
    }

    /**
     * Create an instance of {@link AnularRecogida }
     * 
     */
    public AnularRecogida createAnularRecogida() {
        return new AnularRecogida();
    }

    /**
     * Create an instance of {@link ClsServicio }
     * 
     */
    public ClsServicio createClsServicio() {
        return new ClsServicio();
    }

    /**
     * Create an instance of {@link SolicitarRecogidaConNroRemesa }
     * 
     */
    public SolicitarRecogidaConNroRemesa createSolicitarRecogidaConNroRemesa() {
        return new SolicitarRecogidaConNroRemesa();
    }

    /**
     * Create an instance of {@link ValidarRecogidaOSB }
     * 
     */
    public ValidarRecogidaOSB createValidarRecogidaOSB() {
        return new ValidarRecogidaOSB();
    }

    /**
     * Create an instance of {@link ArrayOfClsServicioRecogidaOut }
     * 
     */
    public ArrayOfClsServicioRecogidaOut createArrayOfClsServicioRecogidaOut() {
        return new ArrayOfClsServicioRecogidaOut();
    }

    /**
     * Create an instance of {@link ClsClienteSolicitanteConNroRemesa }
     * 
     */
    public ClsClienteSolicitanteConNroRemesa createClsClienteSolicitanteConNroRemesa() {
        return new ClsClienteSolicitanteConNroRemesa();
    }

    /**
     * Create an instance of {@link ValidarRecogidaOSBResponse }
     * 
     */
    public ValidarRecogidaOSBResponse createValidarRecogidaOSBResponse() {
        return new ValidarRecogidaOSBResponse();
    }

    /**
     * Create an instance of {@link SolicitarRecogidaConNroRemesaResponse }
     * 
     */
    public SolicitarRecogidaConNroRemesaResponse createSolicitarRecogidaConNroRemesaResponse() {
        return new SolicitarRecogidaConNroRemesaResponse();
    }

    /**
     * Create an instance of {@link ClsSolicitudRecogida }
     * 
     */
    public ClsSolicitudRecogida createClsSolicitudRecogida() {
        return new ClsSolicitudRecogida();
    }

    /**
     * Create an instance of {@link SolicitarRecogidaResponse }
     * 
     */
    public SolicitarRecogidaResponse createSolicitarRecogidaResponse() {
        return new SolicitarRecogidaResponse();
    }

    /**
     * Create an instance of {@link ClsServicioRecogidaOut }
     * 
     */
    public ClsServicioRecogidaOut createClsServicioRecogidaOut() {
        return new ClsServicioRecogidaOut();
    }

    /**
     * Create an instance of {@link Validacionsolicitudrespuesta }
     * 
     */
    public Validacionsolicitudrespuesta createValidacionsolicitudrespuesta() {
        return new Validacionsolicitudrespuesta();
    }

    /**
     * Create an instance of {@link TimeSpan }
     * 
     */
    public TimeSpan createTimeSpan() {
        return new TimeSpan();
    }

    /**
     * Create an instance of {@link ClsServicioRecogidaIn }
     * 
     */
    public ClsServicioRecogidaIn createClsServicioRecogidaIn() {
        return new ClsServicioRecogidaIn();
    }

    /**
     * Create an instance of {@link ClsClienteRemitente }
     * 
     */
    public ClsClienteRemitente createClsClienteRemitente() {
        return new ClsClienteRemitente();
    }

    /**
     * Create an instance of {@link EstadoRecogidaResponse }
     * 
     */
    public EstadoRecogidaResponse createEstadoRecogidaResponse() {
        return new EstadoRecogidaResponse();
    }

    /**
     * Create an instance of {@link Validacionsolicitud }
     * 
     */
    public Validacionsolicitud createValidacionsolicitud() {
        return new Validacionsolicitud();
    }

    /**
     * Create an instance of {@link Respuesta }
     * 
     */
    public Respuesta createRespuesta() {
        return new Respuesta();
    }

    /**
     * Create an instance of {@link ConsultarRecogidaResponse }
     * 
     */
    public ConsultarRecogidaResponse createConsultarRecogidaResponse() {
        return new ConsultarRecogidaResponse();
    }

    /**
     * Create an instance of {@link ClsRecogida }
     * 
     */
    public ClsRecogida createClsRecogida() {
        return new ClsRecogida();
    }

    /**
     * Create an instance of {@link SolicitarRecogida }
     * 
     */
    public SolicitarRecogida createSolicitarRecogida() {
        return new SolicitarRecogida();
    }

    /**
     * Create an instance of {@link EstadoRecogida }
     * 
     */
    public EstadoRecogida createEstadoRecogida() {
        return new EstadoRecogida();
    }

    /**
     * Create an instance of {@link AnularRecogidaResponse }
     * 
     */
    public AnularRecogidaResponse createAnularRecogidaResponse() {
        return new AnularRecogidaResponse();
    }

    /**
     * Create an instance of {@link ClsSolicitudRecogidaConNroRemesa }
     * 
     */
    public ClsSolicitudRecogidaConNroRemesa createClsSolicitudRecogidaConNroRemesa() {
        return new ClsSolicitudRecogidaConNroRemesa();
    }

    /**
     * Create an instance of {@link ConsultarRecogida }
     * 
     */
    public ConsultarRecogida createConsultarRecogida() {
        return new ConsultarRecogida();
    }

    /**
     * Create an instance of {@link ClsServicioConNroRemesa }
     * 
     */
    public ClsServicioConNroRemesa createClsServicioConNroRemesa() {
        return new ClsServicioConNroRemesa();
    }

}
