package ec.com.levelap.tcc.entity.wsrecogidas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-07-07T12:50:14.754-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://clientes.tcc.com.co/", name = "wsRecogidasSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WsRecogidasSoap {

    /**
     * Permite grabar una solicitud de recogida con un número de remesa preasignado.
     */
    @WebMethod(operationName = "SolicitarRecogidaConNroRemesa", action = "http://clientes.tcc.com.co/SolicitarRecogidaConNroRemesa")
    @RequestWrapper(localName = "SolicitarRecogidaConNroRemesa", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsrecogidas.SolicitarRecogidaConNroRemesa")
    @ResponseWrapper(localName = "SolicitarRecogidaConNroRemesaResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsrecogidas.SolicitarRecogidaConNroRemesaResponse")
    public void solicitarRecogidaConNroRemesa(
        @WebParam(name = "clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "SolicitudRecogida", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.entity.wsrecogidas.ClsSolicitudRecogidaConNroRemesa solicitudRecogida,
        @WebParam(name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        int respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta1
    );

    /**
     * Permite grabar una solicitud de recogida.
     */
    @WebMethod(operationName = "SolicitarRecogida", action = "http://clientes.tcc.com.co/SolicitarRecogida")
    @RequestWrapper(localName = "SolicitarRecogida", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsrecogidas.SolicitarRecogida")
    @ResponseWrapper(localName = "SolicitarRecogidaResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsrecogidas.SolicitarRecogidaResponse")
    public void solicitarRecogida(
        @WebParam(name = "clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "SolicitudRecogida", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.entity.wsrecogidas.ClsSolicitudRecogida solicitudRecogida,
        @WebParam(name = "recogida", targetNamespace = "http://clientes.tcc.com.co/")
        int recogida,
        @WebParam(name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        int respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "recogida", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> recogida1,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta1
    );

    /**
     * Permite validar los datos ingresados en una solicitud de recogida.
     */
    @WebMethod(action = "http://clientes.tcc.com.co/validarRecogidaOSB")
    @RequestWrapper(localName = "validarRecogidaOSB", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsrecogidas.ValidarRecogidaOSB")
    @ResponseWrapper(localName = "validarRecogidaOSBResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsrecogidas.ValidarRecogidaOSBResponse")
    @WebResult(name = "validarRecogidaOSBResult", targetNamespace = "http://clientes.tcc.com.co/")
    public ec.com.levelap.tcc.entity.wsrecogidas.Validacionsolicitudrespuesta validarRecogidaOSB(
        @WebParam(name = "clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "SolicitudRecogida", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.entity.wsrecogidas.Validacionsolicitud solicitudRecogida
    );

    /**
     * Anula una recogida, siempre y cuando su estado lo permita
     */
    @WebMethod(operationName = "AnularRecogida", action = "http://clientes.tcc.com.co/AnularRecogida")
    @RequestWrapper(localName = "AnularRecogida", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsrecogidas.AnularRecogida")
    @ResponseWrapper(localName = "AnularRecogidaResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsrecogidas.AnularRecogidaResponse")
    public void anularRecogida(
        @WebParam(name = "clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "Recogida", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.entity.wsrecogidas.ClsRecogida recogida,
        @WebParam(name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        int respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta1
    );

    /**
     * Permite consultar recogidas grabadas para un cliente según los parámetros suministrados
     */
    @WebMethod(operationName = "ConsultarRecogida", action = "http://clientes.tcc.com.co/ConsultarRecogida")
    @RequestWrapper(localName = "ConsultarRecogida", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsrecogidas.ConsultarRecogida")
    @ResponseWrapper(localName = "ConsultarRecogidaResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsrecogidas.ConsultarRecogidaResponse")
    public void consultarRecogida(
        @WebParam(name = "clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "Entrada", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.entity.wsrecogidas.ClsServicioRecogidaIn entrada,
        @WebParam(name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        int respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "ConsultarRecogidaResult", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<ArrayOfClsServicioRecogidaOut> consultarRecogidaResult,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta1
    );

    /**
     * Consulta el estado de una recogida
     */
    @WebMethod(operationName = "EstadoRecogida", action = "http://clientes.tcc.com.co/EstadoRecogida")
    @RequestWrapper(localName = "EstadoRecogida", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsrecogidas.EstadoRecogida")
    @ResponseWrapper(localName = "EstadoRecogidaResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsrecogidas.EstadoRecogidaResponse")
    public void estadoRecogida(
        @WebParam(name = "clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "recogidas", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.entity.wsrecogidas.ArrayOfClsRecogida recogidas,
        @WebParam(mode = WebParam.Mode.INOUT, name = "estRecogida", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> estRecogida,
        @WebParam(name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        int respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta1
    );
}
