package ec.com.levelap.tcc.entity.wsrecogidas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-07-07T12:50:14.868-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "wsRecogidas", 
                  wsdlLocation = "http://clientes.tcc.com.co/servicios/wsrecogidas.asmx?WSDL",
                  targetNamespace = "http://clientes.tcc.com.co/") 
public class WsRecogidas extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://clientes.tcc.com.co/", "wsRecogidas");
    public final static QName WsRecogidasSoap12 = new QName("http://clientes.tcc.com.co/", "wsRecogidasSoap12");
    public final static QName WsRecogidasSoap = new QName("http://clientes.tcc.com.co/", "wsRecogidasSoap");
    public final static QName WsRecogidasHttpGet = new QName("http://clientes.tcc.com.co/", "wsRecogidasHttpGet");
    static {
        URL url = null;
        try {
            url = new URL("http://clientes.tcc.com.co/servicios/wsrecogidas.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsRecogidas.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://clientes.tcc.com.co/servicios/wsrecogidas.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public WsRecogidas(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsRecogidas(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsRecogidas() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsRecogidas(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsRecogidas(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WsRecogidas(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WsRecogidasSoap
     */
    @WebEndpoint(name = "wsRecogidasSoap12")
    public WsRecogidasSoap getWsRecogidasSoap12() {
        return super.getPort(WsRecogidasSoap12, WsRecogidasSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsRecogidasSoap
     */
    @WebEndpoint(name = "wsRecogidasSoap12")
    public WsRecogidasSoap getWsRecogidasSoap12(WebServiceFeature... features) {
        return super.getPort(WsRecogidasSoap12, WsRecogidasSoap.class, features);
    }
    /**
     *
     * @return
     *     returns WsRecogidasSoap
     */
    @WebEndpoint(name = "wsRecogidasSoap")
    public WsRecogidasSoap getWsRecogidasSoap() {
        return super.getPort(WsRecogidasSoap, WsRecogidasSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsRecogidasSoap
     */
    @WebEndpoint(name = "wsRecogidasSoap")
    public WsRecogidasSoap getWsRecogidasSoap(WebServiceFeature... features) {
        return super.getPort(WsRecogidasSoap, WsRecogidasSoap.class, features);
    }
    /**
     *
     * @return
     *     returns WsRecogidasHttpGet
     */
    @WebEndpoint(name = "wsRecogidasHttpGet")
    public WsRecogidasHttpGet getWsRecogidasHttpGet() {
        return super.getPort(WsRecogidasHttpGet, WsRecogidasHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsRecogidasHttpGet
     */
    @WebEndpoint(name = "wsRecogidasHttpGet")
    public WsRecogidasHttpGet getWsRecogidasHttpGet(WebServiceFeature... features) {
        return super.getPort(WsRecogidasHttpGet, WsRecogidasHttpGet.class, features);
    }

}
