//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 01:29:23 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://clientes.tcc.com.co/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ec.com.levelap.tcc.entity.wsDespachos;
