package ec.com.levelap.tcc.entity.wsDespachos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-07-07T12:50:20.209-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://clientes.tcc.com.co/", name = "wsDespachosSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WsDespachosSoap {

    /**
     * Graba un despacho de Paquetería
     */
    @WebMethod(operationName = "GrabarDespacho5", action = "http://clientes.tcc.com.co/GrabarDespacho5")
    @RequestWrapper(localName = "GrabarDespacho5", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.GrabarDespacho5")
    @ResponseWrapper(localName = "GrabarDespacho5Response", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.GrabarDespacho5Response")
    public void grabarDespacho5(
        @WebParam(name = "clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "objDespacho", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.entity.wsDespachos.ClsDespachoPaqueteria5 objDespacho,
        @WebParam(mode = WebParam.Mode.INOUT, name = "remesa", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> remesa,
        @WebParam(name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        int respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta1
    );

    /**
     * Graba un despacho de Paquetería
     */
    @WebMethod(operationName = "GrabarDespacho4", action = "http://clientes.tcc.com.co/GrabarDespacho4")
    @RequestWrapper(localName = "GrabarDespacho4", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.GrabarDespacho4")
    @ResponseWrapper(localName = "GrabarDespacho4Response", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.GrabarDespacho4Response")
    public void grabarDespacho4(
        @WebParam(name = "objDespacho", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.entity.wsDespachos.TpGrabarRemesaCompleta objDespacho,
        @WebParam(mode = WebParam.Mode.INOUT, name = "remesa", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> remesa,
        @WebParam(mode = WebParam.Mode.INOUT, name = "URLRelacionEnvio", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> urlRelacionEnvio,
        @WebParam(mode = WebParam.Mode.INOUT, name = "URLRotulos", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> urlRotulos,
        @WebParam(mode = WebParam.Mode.INOUT, name = "URLRemesa", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> urlRemesa,
        @WebParam(mode = WebParam.Mode.INOUT, name = "IMGRelacionEnvio", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<byte[]> imgRelacionEnvio,
        @WebParam(mode = WebParam.Mode.INOUT, name = "IMGRotulos", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<byte[]> imgRotulos,
        @WebParam(mode = WebParam.Mode.INOUT, name = "IMGRemesa", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<byte[]> imgRemesa,
        @WebParam(name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        int respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta1
    );

    /**
     * Graba los despachos enviado como una relación de envio de Paquetería en modelo Clientes de SION
     */
    @WebMethod(operationName = "GrabarDespacho6", action = "http://clientes.tcc.com.co/GrabarDespacho6")
    @RequestWrapper(localName = "GrabarDespacho6", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.GrabarDespacho6")
    @ResponseWrapper(localName = "GrabarDespacho6Response", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.GrabarDespacho6Response")
    @WebResult(name = "GrabarDespacho6Result", targetNamespace = "http://clientes.tcc.com.co/")
    public ec.com.levelap.tcc.entity.wsDespachos.RelacionEnvioRespuesta grabarDespacho6(
        @WebParam(name = "objDespacho", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.entity.wsDespachos.RelacionEnvio objDespacho
    );

    /**
     * Graba un despacho de Paquetería
     */
    @WebMethod(operationName = "GrabarDespacho", action = "http://clientes.tcc.com.co/GrabarDespacho")
    @RequestWrapper(localName = "GrabarDespacho", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.GrabarDespacho")
    @ResponseWrapper(localName = "GrabarDespachoResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.GrabarDespachoResponse")
    public void grabarDespacho(
        @WebParam(name = "clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "objDespacho", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.entity.wsDespachos.ClsDespachoPaqueteria objDespacho,
        @WebParam(mode = WebParam.Mode.INOUT, name = "remesa", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> remesa,
        @WebParam(name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        int respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta1
    );

    /**
     * Graba un despacho de Paquetería
     */
    @WebMethod(operationName = "GrabarDespacho3", action = "http://clientes.tcc.com.co/GrabarDespacho3")
    @RequestWrapper(localName = "GrabarDespacho3", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.GrabarDespacho3")
    @ResponseWrapper(localName = "GrabarDespacho3Response", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.GrabarDespacho3Response")
    public void grabarDespacho3(
        @WebParam(name = "clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "objDespacho", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.entity.wsDespachos.ClsDespachoPaqueteria3 objDespacho,
        @WebParam(mode = WebParam.Mode.INOUT, name = "remesa", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> remesa,
        @WebParam(name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        int respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta1
    );

    /**
     * Graba un despacho de Paquetería con el segundo esquema de Despacho
     */
    @WebMethod(operationName = "GrabarDespacho2", action = "http://clientes.tcc.com.co/GrabarDespacho2")
    @RequestWrapper(localName = "GrabarDespacho2", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.GrabarDespacho2")
    @ResponseWrapper(localName = "GrabarDespacho2Response", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.GrabarDespacho2Response")
    public void grabarDespacho2(
        @WebParam(name = "clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "objDespacho", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.entity.wsDespachos.ClsDespachoPaqueteria2 objDespacho,
        @WebParam(mode = WebParam.Mode.INOUT, name = "remesa", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> remesa,
        @WebParam(name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        int respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta1
    );

    /**
     * Anula un despacho. Se debe proporcionar el número de remesa y la cuenta del despacho.
     */
    @WebMethod(operationName = "AnularDespacho", action = "http://clientes.tcc.com.co/AnularDespacho")
    @RequestWrapper(localName = "AnularDespacho", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.AnularDespacho")
    @ResponseWrapper(localName = "AnularDespachoResponse", targetNamespace = "http://clientes.tcc.com.co/", className = "ec.com.levelap.tcc.entity.wsDespachos.AnularDespachoResponse")
    public void anularDespacho(
        @WebParam(name = "clave", targetNamespace = "http://clientes.tcc.com.co/")
        java.lang.String clave,
        @WebParam(name = "objDespacho", targetNamespace = "http://clientes.tcc.com.co/")
        ec.com.levelap.tcc.entity.wsDespachos.ClsDespachoPaqueteria objDespacho,
        @WebParam(name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        int respuesta,
        @WebParam(mode = WebParam.Mode.INOUT, name = "mensaje", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.String> mensaje,
        @WebParam(mode = WebParam.Mode.OUT, name = "respuesta", targetNamespace = "http://clientes.tcc.com.co/")
        javax.xml.ws.Holder<java.lang.Integer> respuesta1
    );
}
