package ec.com.levelap.tcc.entity.wsDespachos;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-07-07T12:50:20.141-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://clientes.tcc.com.co/", name = "wsDespachosHttpGet")
@XmlSeeAlso({ObjectFactory.class})
public interface WsDespachosHttpGet {
}
